name: Publish Docker Image
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Pull latest Docker image
        run: docker pull ghcr.io/nolanlum/katheryne:latest
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/nolanlum/katheryne:$GITHUB_SHA --cache-from ghcr.io/nolanlum/katheryne:latest
      - name: Tag image as latest
        run: docker tag ghcr.io/nolanlum/katheryne:$GITHUB_SHA ghcr.io/nolanlum/katheryne:latest
      - name: Push the Docker image
        run: docker push --all-tags ghcr.io/nolanlum/katheryne
